/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resumes */
        get: operations["list_resumes_api_resumes_get"];
        put?: never;
        /** Create Resume */
        post: operations["create_resume_api_resumes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resume */
        get: operations["get_resume_api_resumes__resume_id__get"];
        put?: never;
        post?: never;
        /** Delete Resume */
        delete: operations["delete_resume_api_resumes__resume_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jds/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Jd
         * @description 粘贴 JD → 结构化关键点（预览用，不落库；保存走 POST /jds）。
         */
        post: operations["extract_jd_api_jds_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jds */
        get: operations["list_jds_api_jds_get"];
        put?: never;
        /** Create Jd */
        post: operations["create_jd_api_jds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jds/{jd_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Jd */
        get: operations["get_jd_api_jds__jd_id__get"];
        put?: never;
        post?: never;
        /** Delete Jd */
        delete: operations["delete_jd_api_jds__jd_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Knowledge
         * @description 在当前用户的简历知识库中做语义检索（topK 与阈值走配置）。
         */
        post: operations["search_knowledge_api_knowledge_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Interview
         * @description 创建面试会话（校验简历/JD 归属；返回会话信息，前端跳面试页开首题流）。
         */
        post: operations["start_interview_api_interviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews/{session_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Snapshot
         * @description 会话快照：刷新/重连后重建视图（含是否需要开流生成首题的判定）。
         */
        get: operations["get_snapshot_api_interviews__session_id__snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews/{session_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream First Question
         * @description SSE：生成首题（仅新会话；已推进过的会话返回 done 事件供前端走快照）。
         */
        post: operations["stream_first_question_api_interviews__session_id__stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews/{session_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Answer
         * @description SSE：提交回答 → 判答（评估事件）→ 追问/下一题（流式）。
         */
        post: operations["submit_answer_api_interviews__session_id__answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews/{session_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish Interview
         * @description SSE：提前结束（随时生效）→ 流式收尾总结。
         */
        post: operations["finish_interview_api_interviews__session_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description /health 响应：整体状态 + 运行模式 + 数据库连通性。
         *
         *     - status="ok"：服务与依赖均正常
         *     - status="degraded"：服务在线，但数据库等依赖不可达
         *       （HTTP 仍为 200，便于前端区分「后端不可达」与「依赖降级」）
         *     - status="error"：健康检查自身执行异常（服务可能部分失效），detail 给出原因
         */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "error";
            /** App Llm Mode */
            app_llm_mode: string;
            /** Database */
            database?: ("up" | "down") | null;
            /** Detail */
            detail?: string | null;
        };
        /**
         * InterviewAnswerRequest
         * @description 提交当前问题的回答（提交后进入判答，走 SSE 流式返回评估与下一问题）。
         */
        InterviewAnswerRequest: {
            /** Content */
            content: string;
        };
        /**
         * InterviewQABrief
         * @description 单条问答明细（含追问轮次，回看与快照共用）。
         */
        InterviewQABrief: {
            /** Question Index */
            question_index: number;
            /** Question Type */
            question_type?: string | null;
            /** Question */
            question: string;
            /** Answer */
            answer?: string | null;
            /**
             * Follow Up Round
             * @default 0
             */
            follow_up_round: number;
            /** Assessment */
            assessment?: string | null;
        };
        /**
         * InterviewSessionBrief
         * @description 面试会话简要信息（列表/快照内嵌）。
         */
        InterviewSessionBrief: {
            /** Id */
            id: number;
            /** Resume Id */
            resume_id: number | null;
            /** Jd Id */
            jd_id: number | null;
            /** Role */
            role: string;
            /** Status */
            status: string;
            /** Question Count */
            question_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * InterviewSnapshotResponse
         * @description 面试会话快照：前端刷新/重连后重建视图的唯一数据源。
         *
         *     needs_stream=True 表示当前问题尚未生成（新会话或中断在生成中），
         *     前端应立即打开流式端点获取首题；否则直接展示 current_question 并可作答。
         */
        InterviewSnapshotResponse: {
            session: components["schemas"]["InterviewSessionBrief"];
            /** Phase */
            phase: string;
            /**
             * Question Index
             * @default 0
             */
            question_index: number;
            /**
             * Follow Up Round
             * @default 0
             */
            follow_up_round: number;
            /** Max Questions */
            max_questions: number;
            /** Current Question */
            current_question?: string | null;
            /** Question Type */
            question_type?: string | null;
            /** Summary */
            summary?: string | null;
            /**
             * Needs Stream
             * @default false
             */
            needs_stream: boolean;
            /** Qa History */
            qa_history?: components["schemas"]["InterviewQABrief"][];
        };
        /**
         * InterviewStartRequest
         * @description 开始面试：选择简历与 JD（均须属于当前用户，否则 404）。
         */
        InterviewStartRequest: {
            /** Resume Id */
            resume_id: number;
            /** Jd Id */
            jd_id?: number | null;
        };
        /**
         * JDBrief
         * @description 列表项：不含正文（历史 JD 复选用）。
         */
        JDBrief: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Key Points */
            key_points: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** JDCreateRequest */
        JDCreateRequest: {
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** @description 可选：先经 /jds/extract 提取的结果；缺省时服务端自动提取 */
            key_points?: components["schemas"]["JDKeyPoints"] | null;
        };
        /** JDDetail */
        JDDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Key Points */
            key_points: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Content */
            content: string;
        };
        /** JDExtractRequest */
        JDExtractRequest: {
            /**
             * Content
             * @description JD 原文
             */
            content: string;
        };
        /** JDExtractResponse */
        JDExtractResponse: {
            key_points: components["schemas"]["JDKeyPoints"];
        };
        /**
         * JDKeyPoints
         * @description JD 结构化关键点（LLM 提取结果，E8）。
         */
        JDKeyPoints: {
            /**
             * Position
             * @description 岗位名称
             * @default
             */
            position: string;
            /**
             * Responsibilities
             * @description 核心职责
             */
            responsibilities?: string[];
            /**
             * Required Skills
             * @description 必备技术栈/技能
             */
            required_skills?: string[];
            /**
             * Preferred Skills
             * @description 加分项/优先技能
             */
            preferred_skills?: string[];
            /**
             * Experience Requirements
             * @description 经验与学历要求
             */
            experience_requirements?: string[];
            /**
             * Soft Skills
             * @description 软技能与素质要求
             */
            soft_skills?: string[];
        };
        /** KnowledgeSearchItem */
        KnowledgeSearchItem: {
            /** Content */
            content: string;
            /**
             * Score
             * @description cosine 距离，越小越相关
             */
            score: number;
            /** Resume Id */
            resume_id: number;
            /** Title */
            title: string;
        };
        /** KnowledgeSearchRequest */
        KnowledgeSearchRequest: {
            /**
             * Query
             * @description 检索问题
             */
            query: string;
        };
        /** KnowledgeSearchResponse */
        KnowledgeSearchResponse: {
            /** Results */
            results: components["schemas"]["KnowledgeSearchItem"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Username
             * @description 2–32 位字母/数字/下划线/中文
             */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * ResumeBrief
         * @description 列表项：不含正文。
         */
        ResumeBrief: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ResumeCreateRequest */
        ResumeCreateRequest: {
            /**
             * Title
             * @description 可选标题；缺省取正文首个 H1
             * @default
             */
            title: string;
            /**
             * Content
             * @description Markdown 简历原文
             */
            content: string;
            /**
             * Format
             * @description 简历格式
             * @default markdown
             * @constant
             */
            format: "markdown";
        };
        /** ResumeDetail */
        ResumeDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Content */
            content: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserResponse"];
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_resumes_api_resumes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeBrief"][];
                };
            };
        };
    };
    create_resume_api_resumes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_api_resumes__resume_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_resume_api_resumes__resume_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_jd_api_jds_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JDExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JDExtractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jds_api_jds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JDBrief"][];
                };
            };
        };
    };
    create_jd_api_jds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JDCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JDDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_jd_api_jds__jd_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jd_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JDDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_jd_api_jds__jd_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jd_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_knowledge_api_knowledge_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_interview_api_interviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewSessionBrief"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_api_interviews__session_id__snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewSnapshotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_first_question_api_interviews__session_id__stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_api_interviews__session_id__answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_interview_api_interviews__session_id__finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
